"""
Face Capture & Preprocessing Utility

Goal: Capture a localized dataset to train a PCA-based Face Recognition algorithm. While simple filters can detect where a face is, they cannot differentiate between individual identities—that requires the "Face Space" embeddings generated by PCA, which we will build soon.

Detection: Uses a predefined heuristic filter (Haar Cascade) to localize facial features in real-time.

Standardization: Automatically crops and resizes frames to $64 \times 64$ pixels to maintain parity with the Olivetti face database.

Automation: Each session begins with a directory wipe to prevent data contamination from previous captures.

GUIDELINES: The more images you take of yourself, the better the recognition accuracy will be. While 10 is a minimum, capturing a larger variety of expressions and slight angles helps the model distinguish you more reliably.
"""

import cv2
import os
import shutil

# Create directory if it doesn't exist
output_dir = "./local_demo/data/"
shutil.rmtree(output_dir) # This deletes the folder and everything inside it
os.makedirs(output_dir, exist_ok=True) # recreate folder

face_classifier = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

cam = cv2.VideoCapture(0)
window_name = "Face Capture - Press SPACE to Save, ESC to Exit"
img_counter = 1

while True:
    ret, frame = cam.read()
    if not ret: break

    gray_image = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    # Detect faces
    faces = face_classifier.detectMultiScale(
        gray_image, scaleFactor=1.1, minNeighbors=7, minSize=(110, 110)
    )

    # Draw a rectangle on the display frame so you know it sees you
    display_frame = frame.copy()
    for (x, y, w, h) in faces:
        cv2.rectangle(display_frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    cv2.imshow(window_name, display_frame)

    k = cv2.waitKey(1)
    if k%256 == 27: # ESC
        break
    elif k%256 == 32: # SPACE
        if len(faces) > 0:
            (x, y, w, h) = faces[0] # Take the first face found
            face_crop = gray_image[y:y+h, x:x+w] # Crop to face only
            face_resized = cv2.resize(face_crop, (64, 64)) # Resize to match Olivetti (64x64)
            
            img_name = os.path.join(output_dir, f"face_{img_counter}.png")
            cv2.imwrite(img_name, face_resized)
            print(f"Captured {img_name}")
            img_counter += 1
        else:
            print("No face detected! Try moving closer.")

cam.release()
cv2.destroyAllWindows()